# Note to student: DO NOT EDIT THIS FILE

userBalances: public(HashMap[address,uint256])
    
@external
@payable
def deposit() -> bool:
    self.userBalances[msg.sender] += msg.value
    return True

@external
def withdraw() -> bool:
    #send(msg.sender,self.userBalances[msg.sender])
    #response: Bytes[32] = raw_call(msg.sender,b"\x01", max_outsize=32, value=5)
    #raw_call(msg.sender,0xa9059cbb,value=self.userBalances[msg.sender])
    
    raw_call(msg.sender, b"\0", value=self.userBalances[msg.sender])
    self.userBalances[msg.sender] = 0
    return True